[package]
name = "osm"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.66"
fst = { version = "0.4.7", features = ["levenshtein"] }
geo = { version = "0.23.0", features = ["serde"] }
geojson = "0.24.0"
osmpbfreader = "0.15.2"
rayon = "1.6.0"
serde_json = "1.0.89"
